{"name": "Realizar transferencia entre contas com sucesso", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/transferencias/steps/steps_transferencia_entre_contas.py\", line 53, in step_impl\n    context.Transferencia.valida_texto_transferencia_realizada('Transferencia realizada com sucesso')\n  File \"/home/runner/work/Desafio-BugBank/Desafio-BugBank/features/transferencias/mapping/actions/transferencia.py\", line 28, in valida_texto_transferencia_realizada\n    assert texto in texto_retornado\n"}, "steps": [{"name": "Dado que eh realizado o cadastro de um usuario \"principal\"", "status": "passed", "start": 1710658903532, "stop": 1710658904248}, {"name": "E que eh realizado o cadastro de um usuario \"secundario\" para receber uma transferencia", "status": "passed", "start": 1710658904249, "stop": 1710658907726}, {"name": "E que eh realizado o login com um usuario \"principal\"", "status": "passed", "start": 1710658907726, "stop": 1710658908057}, {"name": "Quando entrar na pagina de transferencia entre contas", "status": "passed", "start": 1710658908057, "stop": 1710658908620}, {"name": "E realizar uma transferencia entre contas para um usuario secundario", "status": "passed", "start": 1710658908620, "stop": 1710658909863}, {"name": "Entao deve ser validado o texto no popup de conclusao de transferencia", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/transferencias/steps/steps_transferencia_entre_contas.py\", line 53, in step_impl\n    context.Transferencia.valida_texto_transferencia_realizada('Transferencia realizada com sucesso')\n  File \"/home/runner/work/Desafio-BugBank/Desafio-BugBank/features/transferencias/mapping/actions/transferencia.py\", line 28, in valida_texto_transferencia_realizada\n    assert texto in texto_retornado\n"}, "start": 1710658909864, "stop": 1710658911205}], "start": 1710658894039, "stop": 1710658911264, "uuid": "1de6c711-25a7-4acc-a3b4-02a82329c33f", "historyId": "711407fcaf99f8aac434b53766787913", "fullName": "Transferencia Entre Contas: Realizar transferencia entre contas com sucesso", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Transferencia Entre Contas"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}